[Server]
iface = "enp3s0"
#Interface to listen on
driver = "libpcap"
#Data AcQuisition packet source: pcapgo, libpcap, AF_PACKET or BSD_BPF.BSD_BPF is BSD systems only.AF_PACKET is Linux only.libpcap builds on Linux and FreeBSD and can read every kind of pcap format.pcapgo builds on every platform but does not support pcap-ng format, only pcap v2.4.
backend = "file://zone.d/protobuf/"
worker_num = 24

[Log]
level = "INFO"
#FINE|DEBUG|TRACE|INFO|WARN|ERROR"

